dojot/history

- history/sample/models.py
* Moves query parsing to a common routine, allowing better reuse.
* Include date(from|to) filters when querying stored history.
> Refactors query parsing, adds missing period limit options

- history/api/models.py
This is connected to dojot/dojot#199
> Small fixes related to device_type on STH-compatible API

- history/subscriber/kafkaSubscriber.py
This is connected to dojot/dojot#259
> Kill all subprocesses on error

- history/api/models.py
> Better handle invalid parameter values for lastN

- history/subscriber/kafkaSubscriber.py
This is closes dojot/gui#94
This is connected to dojot/dojot#272
> Fixes timestamp parsing for persister service

- .travis.yml
- docs/history.apib
- tests/Dockerfile
- tests/docker-compose.yml
- tests/dredd-hooks/authentication_hook.py
- tests/dredd-hooks/operation_hook.py
- tests/dredd-hooks/token_generator.py
- tests/requirements.txt
- tests/start-test.sh
- travis/publish.sh
Needs first the dreed+python2 docker image
> Creates APIB definition an test component with it

- history/subscriber/kafkaSubscriber.py
This fixes the persistence of device status information as it is produced by `device-manager`.
> Fixes parsing of status updates

- history/conf.py
- history/subscriber/kafkaSubscriber.py
Adds MongoDB sharding capability.
No sharding available.
Persister is able to send sharding commands to MongoDB.
No breaking changes.
> Adds MongoDB sharding capability

- history/subscriber/kafkaSubscriber.py
Code refactor and a bit of performance improvement.
Persister always tries to shard and create indexes when handling incoming data or device management.
Since MongoDB was separated into a static class, there will be no duplicate instances. Also, shard and index creation will not be requested more than once.
No breaking changes.
* **Is there any issue related to this PR in other …
> MongoDB class separation

- tests/performance_tests/README.md
- tests/performance_tests/docker-compose.yml
- tests/performance_tests/kafkaSubscriber.py
- tests/performance_tests/requirements.txt
- tests/performance_tests/script.py
- tests/performance_tests/token.js
Persister performance test
This is connected to dojot/dojot#715.
> delay time for messages performance test

- docker/history.docker
- docker/persister.docker
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR greatly reduces Docker image size for both persister and history, with no observable impact on functionality.
Image is around 900MB.
Image size is reduced to 95MB.
No.
* **Is there any issue related to this PR in other repository?** (such as …
> ci: checking image build, reducing docker size

- history/subscriber/persister.py
This PR filters out unwanted (or unknown) messages related to devices
All messages are processed but "configure". 
Only "device.create", "device.update" and "configure" messages are processed.
No
This is connected to dojot/dojot#828
> fix: ignoring any unwanted messages

- history/subscriber/persister.py
- requirements/requirements.txt
This PR updates the version for dojot.module library.
Persister doesn't die when any problem occurs.
It dies.
No.
This is related to dojot/dojot#824
> Updating dojot.module version

- .travis.yml
- history/subscriber/persister.py
- tests/dredd-hooks/operation_hook.py
feature
All not recognize metadata all discarded.
All not recognize metadata are saved into the attribute 'metadata'.
No
No
The recognized metadata are: 'deviceid', 'timestamp' and 'tenant'
> Adds support to metadata on device_data events

- history/subscriber/persister.py
Removes a legacy feature.
The device status is persisted. ( this event is not supported anymore by the device manager)
The device status is not persisted any more.
No
> Removes support to device status

- docs/history.apib
- [NA] Tests for the changes have been added (for bug fixes / features)
Documentation update
No
This is connected to dojot/dojot#717
> Review of history API documentation

- history/subscriber/persister.py
Bug fix
Now Persist timestamp receive 
This is connected to dojot/dojot#1105
> Fix: Real time for actuator

- history/subscriber/persister.py
This commit removes the timestamp from metadata only if it
exists
> Properly remove timestamp from metadata

- history/api/models.py
Correct status code when notifications list is empty
Return http 404 when the notifications list is empty
Return http 200 with empty notifications list
No
Yes, this PR is connected to dojot/dojot#996
> fix api not found

- history/subscriber/persister.py
bugfix
the persister become a zombie when it receives a message with a non-object attributes 'attrs' 
No
dojot/dojot#893
> Fixes broken log message

- history/subscriber/persister.py
Metrics for performance tests
There are not metrics for performance tests
Thare are metricis for performance tests
No
Yes, is connected to dojot/dojot#1154
That feature is just for tests.
> metrics for performance tests

- .travis.yml
Bug fix
The documentation is not published
dojot/dojot#588
> fix: Documentation update

- .travis.yml
- travis/deploy-gh-pages.sh
Bug fix
Improve time to run travis without install aglio
dojot/dojot#1190
> chore: improve time travis

- history/subscriber/persister.py
Corrects persister when cron node sends a wrong configuration
> Corrects persister when cron node configuration is wrong

- travis/deploy-gh-pages.sh
https://github.com/dojot/dojot/issues/1252
Publishing documentation
> fix: travis publish doc

- history/subscriber/persister.py
- requirements/requirements.txt
dojot/dojot#1246, dojot/dojot#1254
> Release V0.4.1 

- history/subscriber/persister.py
add index that is  actually used in history  
https://github.com/dojot/history/blob/4e17acf61bd64ffbd48f0a2cc05210c82d3475ca/history/api/models.py#L126
and fix event value
Depends https://github.com/dojot/history/pull/73
> fix: add index and fix event create 

- docs/just-for-testing.apib
- tests/apptests.py
- tests/dredd-hooks/operation_hook.py
- tests/start-test.sh
- travis/deploy-gh-pages.sh
dojot/dojot#1457
The history APi is not well designed, I tried to describe all its particularities for the user in the documentation, however such details do not work well with the automatic dreed tests. So, I decided to create 2 files, one to generate the documentation and one …
> doc: More detail on api documentation [0.5]

- docs/just-for-testing.apib
- tests/apptests.py
- tests/dredd-hooks/operation_hook.py
- tests/start-test.sh
- travis/deploy-gh-pages.sh
dojot/dojot#1457
The history APi is not well designed, I tried to describe all its particularities for the user in the documentation, however such details do not work well with the automatic dreed tests. So, I decided to create 2 files, one to generate the documentation and one …
> doc: More detail on api documentation  [dev]

- history/api/models.py
- history/app.py
- history/conf.py
bug fix
- There were not many logs in the component;
- When the LOG_LEVEL environment variable was set to a minuscule value, there was a problem with the component initialization;
- When the environment variable LOG_LEVEL was initialized with the value INFO and later, if the admin wanted to change this value to DEBUG, the debug messages were not logged.
- more logs have been added to the functions;
- env_var LOG_LEVEL value converted to uppercase;
- The error that occurred when trying to change the log level …
> [release/v0.5.0] History - Correction of problems with the logger

- history/subscriber/persister.py
> fix: stops when it receives a payload without attrs [0.4.4]

- history/subscriber/persister.py
- tests/test_subscriber.py
> fix: stops when it receives a payload without attrs [dev]

- history/subscriber/persister.py
- tests/test_subscriber.py
> fix: stops when it receives a payload without attrs [0.5.0]

- docs/history.apib
- history/api/models.py
feature
It is only possible to sort by the last data registered in the bank
It is possible to sort by the first data registered in the bank (the oldest ones)
no
dojot/dojot#1701
> [release v0.4.4] History - Allow "First N" query

- LICENSE
- NOTICE
- history/__init__.py
- requirements/requirements.txt
It licenses the 'history' and 'persiter' services under Apache License.
NA
NA
No
dojot/dojot#1879
> Licensed the 'history' and 'persister' services under Apache-2.0 License

- LICENSE
- NOTICE
- history/__init__.py
- requirements/requirements.txt
> [v0.5.2] Cherry-picking licenses from development 

- LICENSE
- NOTICE
- history/__init__.py
- requirements/requirements.txt
Be careful, see if it is necessary to update the branch! **Most likely it is not to update.**
> Merge version v0.5.2 from branch release/v0.5.2 to branch master

- .gitignore
- history/api/models.py
- requirements/requirements.txt
dojot/dojot#1986
the main change is at line 70 on history/api/models.py
> Changes to using keycloak 

- .gitignore
- history/api/models.py
- requirements/requirements.txt
> Add Feature/keycloak branch to development branch

- .gitignore
- history/api/models.py
- requirements/requirements.txt
> Revert "Add Feature/keycloak branch to development branch"

- history/api/models.py
- tests/test_notification_history.py
> feat: receive timestamp range for search and change data return limit

- history/api/models.py
- tests/test_notification_history.py
> feat: get all notifications if filter parameters are passed

- docker/persister.docker
- history/subscriber/persister.py
- requirements/persister.txt
> FIx TTL error

- docker/persister.docker
- requirements/persister.txt
- setup.py
Update
The service persister does't start running.
The service persists has independent build process now.
* dojot/dojot#2182
> [Dev] Update: split persister's requirements

- history/subscriber/persister.py
- tests/test_subscriber.py
> MongoDB - Allow changing data expiration time

- docs/history.apib
- history/app.py
> [0.7.1] [History] Fix: docs
